### ISSUE TITLE
File auto deleted on launch

### ISSUE THREAD

**Issue by pistou** [e0xify/KodiXBMCTextureTool#1]
When I try to launch `Kodi.texture.exe`, I have a Windows notification that says there is an update and it will do automatically.
One or two minutes after, I have a console automatically launched, too fast to be abble to rzad something, then `Kodi.Texture.exe` is deleted.

For the record, I'm on Windows 10

**Comment by suppqt** [comment]
that happens when update server is unavaiable, an issue i will fix.
host is now available. should work without problems
